# Uncomment this when you reach the "Use the Force" section
train_mass = 22680
train_acceleration = 10
train_distance = 100
bomb_mass = 1
c = (3 * (10 ** 8))

# Write your code below: 

def f_to_c(f_temp):
  c_temp = ((f_temp - 32) * 5/9)
  return c_temp

#if right the above should convert a temperature in F to degrees C

f100_in_celsius = f_to_c(100)

#correct response given when printed

def c_to_f(c_temp):
  f_temp = ((c_temp * (9/5)) + 32)
  return f_temp

#This should convert degrees C to degrees F

c0_in_fharenheit = c_to_f(0)

#so far so good. Correct response and no errors

def get_force(mass, acceleration):
  force = (mass * acceleration)
  return force
train_force = get_force(train_mass, train_acceleration)

#I'm scared that everything has worked so far. No errors, still recieving correct responsed, simple equations

print('The GE train supplies ' + str(train_force) + ' Newtons of force.')

def get_energy(mass, c):
  energy = (mass * (c ** 2))
  return energy
bomb_energy = get_energy(bomb_mass, c)

#errors now resolved, all responses seem to be as expected

print('A 1kg bomb supplies ' + str(bomb_energy) + ' Joules.')

#so all is functioning properly

def get_work(mass, acceleration, distance):
  work = (train_force * distance)
  return work
train_work = get_work(train_mass, train_acceleration, train_distance)
print('The GE train does ' + str(train_work) + ' Joules over ' + str(train_distance) + ' meters.')
